### ISSUE TITLE
Collect all evaluation results for current models

### ISSUE THREAD

**Issue by nightingal3** [nightingal3/llm-pretraining-behaviours#122]
We have a [script](https://github.com/nightingal3/llm-pretraining-behaviours/blob/main/metadata/collect_integrated_model_scores.py) to collect hf leaderboard results/eval harness results for models, but we should check to make sure it still works to collect results for all the models in `metadata/model_metadata` (or at least all the models listed under `id` here: https://docs.google.com/spreadsheets/d/1MIrVzM51ryJIMu52CLSe45Ej_HUQajH9Bo-_34r0ADw/edit#gid=1374859561)

- If possible, we may also want to change this script since the way it does things now is a bit ugly -- for context we originally were just looking up huggingface leaderboard results, hence the first search through the leaderboard dataset and then the subprocess call to eval harness.

- [ ] Collect new model results for the models in the sheet using the task groups in `eval_task_groups/reasoning_*.yml`
- [ ] (possibly) change the script to be more consistent, e.g. only using eval harness, and changing "x-shot" to the actual number of ICL examples

**Comment by lintangsutawika** [comment]
I can take a look at this. Do we have a complete list of tasks we want to run all the models on? I can run them on all of the models listed as well.

**Comment by lintangsutawika** [comment]
Also, should the collected data be in a csv for easier parsing via pandas?
